apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjsdemo
  namespace: sample-namespace
spec:
  selector:
    matchLabels:
      app: reactjsdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: reactjsdemo
    spec:
      containers:
      - image: gcr.io/niveusanthos/reactjsdemo:3.0.0
        imagePullPolicy: Always
        name: reactjsdemo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactjsdemo
  namespace: sample-namespace
spec:
  type: LoadBalancer
  selector:
    app: reactjsdemo
  ports:
  - name: http
    port: 80
    targetPort: 80