apiVersion: apps/v1
kind: Deployment
metadata:
  name: versionservice-v1
  namespace: sample-namespace
  labels:
    version: v1
spec:
  selector:
      matchLabels:
        app: versionservice
  replicas: 1
  template:
    metadata:
      labels:
        app: versionservice
        version: v1
    spec:
      containers:
        - name: versionservice
          image: gcr.io/niveusanthos/versionservice:3.0.0
          ports:
            - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versionservice-v2
  namespace: sample-namespace
  labels:
    version: v2
spec:
  selector:
      matchLabels:
        app: versionservice
  replicas: 1
  template:
    metadata:
      labels:
        app: versionservice
        version: v2
    spec:
      containers:
        - name: versionservice
          image: gcr.io/niveusanthos/versionservice-v2:1.0.0
          ports:
            - containerPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: versionservice
  namespace: sample-namespace
spec:
  selector:
    app: versionservice
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  type: ClusterIP